apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-job
spec:
  minAvailable: 3
  schedulerName: kube-batch
  policies:
  - event: PodEvicted
    action: RestartJob
  input:
    mountPath: "/myinput"
  output:
    mountPath: "/myoutput"
    volumeClaim:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
  tasks:
  - replicas: 6
    name: "default-nginx"
    template:
      metadata:
        name: web
      spec:
        containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: nginx
          resources:
            requests:
              cpu: "1"
        restartPolicy: OnFailure
