apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cronjobs.batch.volcano.sh
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: batch.volcano.sh
  names:
    kind: CronJob
    plural: cronjobs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            schedule:
              description: The cron expression for CronJob
              type: string
            template:
              description: Specification of the desired behavior of a cron job, including
                the minAvailable
              properties:
                input:
                  description: The volume mount for input of Job
                  properties:
                    volumeClaim:
                      description: VolumeClaim defines the PVC used by the VolumeMount.
                      type: object
                    mountPath:
                      description: Path within the container at which the volume should
                        be mounted.  Must not contain ':'.
                      type: string
                  required:
                    - mountPath
                  type: object
                minAvailable:
                  description: The minimal available pods to run for this Job
                  format: int32
                  type: integer
                output:
                  description: The volume mount for output of Job
                  properties:
                    volumeClaim:
                      description: VolumeClaim defines the PVC used by the VolumeMount.
                      type: object
                    mountPath:
                      description: Path within the container at which the volume should
                        be mounted.  Must not contain ':'.
                      type: string
                  required:
                    - mountPath
                  type: object
                policies:
                  description: Specifies the default lifecycle of tasks
                  items:
                    properties:
                      action:
                        description: The action that will be taken to the PodGroup according
                          to Event. One of "Restart", "None". Default to None.
                        type: string
                      event:
                        description: The Event recorded by scheduler; the controller takes
                          actions according to this Event.
                        type: string
                      timeout:
                        description: Timeout is the grace period for controller to take
                          actions. Default to nil (take action immediately).
                        type: object
                    type: object
                  type: array
                schedulerName:
                  description: SchedulerName is the default value of `tasks.template.spec.schedulerName`.
                  type: string
                tasks:
                  description: Tasks specifies the task specification of Job
                  items:
                    properties:
                      name:
                        description: Name specifies the name of tasks
                        type: string
                      policies:
                        description: Specifies the lifecycle of task
                        items:
                          properties:
                            action:
                              description: The action that will be taken to the PodGroup
                                according to Event. One of "Restart", "None". Default
                                to None.
                              type: string
                            event:
                              description: The Event recorded by scheduler; the controller
                                takes actions according to this Event.
                              type: string
                            timeout:
                              description: Timeout is the grace period for controller
                                to take actions. Default to nil (take action immediately).
                              type: object
                          type: object
                        type: array
                      replicas:
                        description: Replicas specifies the replicas of this TaskSpec
                          in Job
                        format: int32
                        type: integer
                      template:
                        description: Specifies the pod that will be created for this TaskSpec
                          when executing a Job
                        type: object
                    type: object
                  type: array
              type:
                object
            suspend:
              description: Whether the CronJob has been suspended.
              type: boolean
          type:
            object
        status:
          description: Current status of CronJob
          properties:
            lastRun:
              description: LastRun is the time when the last job started.
              type: string
            nextRun:
              description: NextRun is the time when the next run of Job will start.
              type: string
            lastRunName:
              description: LastRunName is the name of the last run Job.
              type: string
          type: object
  version: v1alpha1
  subresources:
    status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
