# this config file contains all config fields with comments
kind: Config
apiVersion: kind.sigs.k8s.io/v1alpha2
# 1 control plane node and 3 workers
nodes:
  # the control plane node config
  - role: control-plane
  # the three workers
  - role: worker
    # replicas specifies the number of nodes to create with this configuration
    replicas: 4
