name: Code Verify

on:
  push:
    branches:
      - master
    tags:
  pull_request:

permissions:  
  contents: read

jobs:
  verify:
    runs-on: ubuntu-24.04
    name: Verify codes, generated files
    timeout-minutes: 40
    env:
      GOPATH: /home/runner/work/${{ github.repository }}
    steps:
      - name: Install Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.22.x

      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
          path: ./src/github.com/${{ github.repository }}

      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run verify test
        run: |
          make lint
          make verify
          make TAG=latest generate-yaml
          make verify-generated-yaml
          make unit-test
        working-directory: ./src/github.com/${{ github.repository }}
