name: E2E Spark Integration Test

on:
  pull_request:

jobs:
  k8s-integration-tests:
    name: Run K8S integration tests with volcano
    runs-on: self-hosted
    env:
      SPARK_LOCAL_IP: localhost
      GOPATH: /home/runner/work/${{ github.repository }}
    steps:
    - name: Checkout Spark repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: apache/spark
        ref: master
    - name: Checkout Spark repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: volcano-sh/volcano
        ref: master
    - name: Install Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: start minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start
    - name: Build lastest volcano images
      run: |
        eval $(minikube docker-env)
        make TAG=spark generate-yaml
        make verify-generated-yaml
        make TAG=spark images
    - name: Show all K8S pods and nodes
      run: |
        kubectl get pods -A
        kubectl get nodes -oyaml
    - name: Run K8S integration test
      run: |
        kubectl create clusterrolebinding serviceaccounts-cluster-admin --clusterrole=cluster-admin --group=system:serviceaccounts || true
        eval $(minikube docker-env)
        build/sbt -Pvolcano -Pkubernetes -Pkubernetes-integration-tests -Dtest.exclude.tags=minikube,r,local -Dtest.include.tags=volcano "kubernetes-integration-tests/test"
      working-directory: $GITHUB_WORKSPACE/apache/spark
    - name: Cleanup minikube
      run: |
        minikube delete
