name: Scheduling Actions

on:
  push:
    branches:
      - master
    tags:
  pull_request:

permissions:  
  contents: read

jobs:
  e2e_scheduling_actions:
    runs-on: ubuntu-24.04
    name: E2E about Scheduling Actions
    timeout-minutes: 40
    steps:
      - name: Install Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.22.x

      - name: Install musl
        run: |
          wget http://musl.libc.org/releases/musl-1.2.1.tar.gz
          tar -xf musl-1.2.1.tar.gz && cd musl-1.2.1
          ./configure
          make && sudo make install
      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install dependences
        run: |
          GO111MODULE="on" go install sigs.k8s.io/kind@v0.23.0
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.30.1/bin/linux/amd64/kubectl && sudo install kubectl /usr/local/bin/kubectl
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Run E2E Tests
        run: |
          make e2e-test-schedulingaction CC=/usr/local/musl/bin/musl-gcc