name: FOSSA
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:  
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.22.x
      - run: go version
      # Runs a set of commands to initialize and analyze with FOSSA
      - name: run FOSSA analysis
        env:
          # FOSSA Push-Only API Token
          FOSSA_API_KEY: '1a92b8d8ee4304c0ad85a726b9e9acab'
          BINDIR: /home/runner/work/volcano/volcano
        run: |
          export GOPATH=$HOME/go
          export PATH=$PATH:$(go env GOPATH)/bin
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash -s -- -b /home/runner/work/volcano/volcano 
          /home/runner/work/volcano/volcano/fossa init
          /home/runner/work/volcano/volcano/fossa analyze
