name: Licenses Lint

on:
  push:
    branches:
      - master
    tags:
  pull_request:

permissions:  
  contents: read

jobs:
  licenses-lint:
    name: Licenses Lint
    timeout-minutes: 40
    runs-on: ubuntu-22.04
    steps:
      - name: Install Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.21.x
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: generate license mirror
        run: |
          make licenses-check
      - name: lint-licenses
        # if restricted > 0, CI will report an error.
        run: |
          make lint-licenses
